import { NextResponse } from "next/server";
import { prisma } from "@/lib/db/prisma";
import { requirePermission, getAccessibleBranchIds } from "@/lib/auth/authorization";
import { defaultBranchId } from "@/lib/api/branches";
import { apiErrorFromUnknown } from "@/lib/api/response";

const statusMap: Record<string, "NEW" | "POTENTIAL" | "CONVERTED" | "UNQUALIFIED"> = { "Mới": "NEW", "Tiềm năng": "POTENTIAL", "Đã chuyển đổi": "CONVERTED", "Không phù hợp": "UNQUALIFIED" };
const labelMap = { NEW: "Mới", POTENTIAL: "Tiềm năng", CONVERTED: "Đã chuyển đổi", UNQUALIFIED: "Không phù hợp" };
const toResponse = (x: any) => ({ id: x.id, name: x.fullName, phone: x.phone, source: x.source ?? "", status: labelMap[x.status as keyof typeof labelMap] });

export async function GET() { try { await requirePermission("lead.read"); const ids = await getAccessibleBranchIds(); const leads = await prisma.lead.findMany({ where: ids === null ? {} : { branchId: { in: ids } }, orderBy: { createdAt: "desc" } }); return NextResponse.json({ data: leads.map(toResponse) }); } catch (e) { return apiErrorFromUnknown(e, "Không thể lấy danh sách Lead."); } }
export async function POST(request: Request) { try { const user = await requirePermission("lead.create"); const b = await request.json(); const branchId = String(b.branchId ?? await defaultBranchId()).trim(); if (!branchId || !String(b.name ?? "").trim() || !String(b.phone ?? "").trim()) return NextResponse.json({ message: "Chi nhánh, họ tên và số điện thoại là bắt buộc." }, { status: 400 }); const lead = await prisma.lead.create({ data: { branchId, fullName: String(b.name).trim(), phone: String(b.phone).trim(), source: String(b.source ?? "").trim() || null, status: statusMap[String(b.status ?? "Mới")] ?? "NEW", createdById: user.id, updatedById: user.id } }); return NextResponse.json({ data: toResponse(lead) }, { status: 201 }); } catch (e) { return apiErrorFromUnknown(e, "Không thể tạo Lead."); } }
export async function PATCH(request: Request) { try { const user = await requirePermission("lead.update"); const b = await request.json(); const ids = await getAccessibleBranchIds(); const existing = await prisma.lead.findFirst({ where: { id: String(b.id), ...(ids === null ? {} : { branchId: { in: ids } }) } }); if (!existing) return NextResponse.json({ message: "Không tìm thấy Lead." }, { status: 404 }); const lead = await prisma.lead.update({ where: { id: existing.id }, data: { fullName: String(b.name ?? existing.fullName).trim(), phone: String(b.phone ?? existing.phone).trim(), source: String(b.source ?? existing.source ?? "").trim() || null, status: statusMap[String(b.status)] ?? existing.status, updatedById: user.id } }); return NextResponse.json({ data: toResponse(lead) }); } catch (e) { return apiErrorFromUnknown(e, "Không thể cập nhật Lead."); } }
export async function DELETE(request: Request) { try { await requirePermission("lead.delete"); const b = await request.json(); const ids = await getAccessibleBranchIds(); const existing = await prisma.lead.findFirst({ where: { id: String(b.id), ...(ids === null ? {} : { branchId: { in: ids } }) }, select: { id: true } }); if (!existing) return NextResponse.json({ message: "Không tìm thấy Lead." }, { status: 404 }); await prisma.lead.delete({ where: { id: existing.id } }); return NextResponse.json({ message: "Đã xóa Lead." }); } catch (e) { return apiErrorFromUnknown(e, "Không thể xóa Lead."); } }
