import { NextResponse } from "next/server";
import { prisma } from "@/lib/db/prisma";
import { requirePermission, getAccessibleBranchIds } from "@/lib/auth/authorization";
import { defaultBranchId } from "@/lib/api/branches";
import { apiErrorFromUnknown } from "@/lib/api/response";
const out = (x: any) => ({ id: x.id, name: x.name, value: x.value, group: x.group });
export async function GET() { try { await requirePermission("settings.read"); const ids = await getAccessibleBranchIds(); const rows = await prisma.gymSetting.findMany({ where: ids === null ? {} : { branchId: { in: ids } }, orderBy: { name: "asc" } }); return NextResponse.json({ data: rows.map(out) }); } catch (e) { return apiErrorFromUnknown(e, "Không thể lấy cài đặt."); } }
export async function POST(request: Request) { try { await requirePermission("settings.update"); const b = await request.json(); const branchId = String(b.branchId ?? await defaultBranchId()).trim(); const row = await prisma.gymSetting.create({ data: { branchId, name: String(b.name).trim(), value: String(b.value).trim(), group: String(b.group ?? "Hệ thống") } }); return NextResponse.json({ data: out(row) }, { status: 201 }); } catch (e) { return apiErrorFromUnknown(e, "Không thể tạo cài đặt."); } }
export async function PATCH(request: Request) { try { await requirePermission("settings.update"); const b = await request.json(); const row = await prisma.gymSetting.update({ where: { id: String(b.id) }, data: { name: String(b.name), value: String(b.value), group: String(b.group) } }); return NextResponse.json({ data: out(row) }); } catch (e) { return apiErrorFromUnknown(e, "Không thể cập nhật cài đặt."); } }
export async function DELETE(request: Request) { try { await requirePermission("settings.update"); const b = await request.json(); await prisma.gymSetting.delete({ where: { id: String(b.id) } }); return NextResponse.json({ message: "Đã xóa cài đặt." }); } catch (e) { return apiErrorFromUnknown(e, "Không thể xóa cài đặt."); } }