import { NextResponse } from "next/server";
import { prisma } from "@/lib/db/prisma";
import { requirePermission, getAccessibleBranchIds } from "@/lib/auth/authorization";
import { defaultBranchId } from "@/lib/api/branches";
import { apiErrorFromUnknown } from "@/lib/api/response";
const methodMap: Record<string, "CASH" | "BANK_TRANSFER" | "CARD"> = { "Tiền mặt": "CASH", "Chuyển khoản": "BANK_TRANSFER", "Thẻ": "CARD" };
const statusMap: Record<string, "PAID" | "PENDING" | "CANCELLED"> = { "Đã thanh toán": "PAID", "Chờ thanh toán": "PENDING", "Đã hủy": "CANCELLED" };
const methodLabel = { CASH: "Tiền mặt", BANK_TRANSFER: "Chuyển khoản", CARD: "Thẻ" }; const statusLabel = { PAID: "Đã thanh toán", PENDING: "Chờ thanh toán", CANCELLED: "Đã hủy" };
const out = (x: any) => ({ id: x.id, member: x.member.fullName, memberId: x.memberId, amount: Number(x.amount), method: methodLabel[x.method as keyof typeof methodLabel], status: statusLabel[x.status as keyof typeof statusLabel], date: (x.paidAt ?? x.createdAt).toISOString().slice(0, 10) });
export async function GET() { try { await requirePermission("payment.read"); const ids = await getAccessibleBranchIds(); const rows = await prisma.payment.findMany({ where: ids === null ? {} : { branchId: { in: ids } }, include: { member: true }, orderBy: { createdAt: "desc" } }); return NextResponse.json({ data: rows.map(out) }); } catch (e) { return apiErrorFromUnknown(e, "Không thể lấy giao dịch."); } }
export async function POST(request: Request) { try { await requirePermission("payment.create"); const b = await request.json(); const memberId = String(b.memberId ?? "").trim(); const member = await prisma.member.findUnique({ where: { id: memberId } }); const amount = Number(b.amount); if (!member || !Number.isFinite(amount) || amount < 0) return NextResponse.json({ message: "Hội viên hoặc số tiền không hợp lệ." }, { status: 400 }); const row = await prisma.payment.create({ data: { branchId: member.branchId, memberId, amount, method: methodMap[String(b.method)] ?? "CASH", status: statusMap[String(b.status)] ?? "PAID", paidAt: b.date ? new Date(b.date) : new Date() }, include: { member: true } }); return NextResponse.json({ data: out(row) }, { status: 201 }); } catch (e) { return apiErrorFromUnknown(e, "Không thể tạo giao dịch."); } }
export async function PATCH(request: Request) { try { await requirePermission("payment.update"); const b = await request.json(); const ids = await getAccessibleBranchIds(); const existing = await prisma.payment.findFirst({ where: { id: String(b.id), ...(ids === null ? {} : { branchId: { in: ids } }) } }); if (!existing) return NextResponse.json({ message: "Không tìm thấy giao dịch." }, { status: 404 }); const row = await prisma.payment.update({ where: { id: existing.id }, data: { amount: Number(b.amount ?? existing.amount), method: methodMap[String(b.method)] ?? existing.method, status: statusMap[String(b.status)] ?? existing.status, paidAt: b.date ? new Date(b.date) : existing.paidAt }, include: { member: true } }); return NextResponse.json({ data: out(row) }); } catch (e) { return apiErrorFromUnknown(e, "Không thể cập nhật giao dịch."); } }
export async function DELETE(request: Request) { try { await requirePermission("payment.delete"); const b = await request.json(); const ids = await getAccessibleBranchIds(); const existing = await prisma.payment.findFirst({ where: { id: String(b.id), ...(ids === null ? {} : { branchId: { in: ids } }) } }); if (!existing) return NextResponse.json({ message: "Không tìm thấy giao dịch." }, { status: 404 }); await prisma.payment.update({ where: { id: existing.id }, data: { status: "CANCELLED" } }); return NextResponse.json({ message: "Đã hủy giao dịch." }); } catch (e) { return apiErrorFromUnknown(e, "Không thể hủy giao dịch."); } }