import { NextResponse } from "next/server";
import { prisma } from "@/lib/db/prisma";
import { requirePermission, getAccessibleBranchIds } from "@/lib/auth/authorization";
import { defaultBranchId } from "@/lib/api/branches";
import { apiErrorFromUnknown } from "@/lib/api/response";
const label = (s: string) => s === "ACTIVE" ? "Đang bán" : "Tạm dừng";
const map = (x: any) => ({ id: x.id, name: x.name, duration: Math.round(x.durationDays / 30), price: Number(x.price), status: label(x.status) });
export async function GET(request: Request) { try { await requirePermission("member.read"); const ids = await getAccessibleBranchIds(); const status = new URL(request.url).searchParams.get("status"); const rows = await prisma.gymPackage.findMany({ where: { ...(ids === null ? {} : { branchId: { in: ids } }), ...(status === "ACTIVE" || status === "INACTIVE" ? { status } : {}) }, orderBy: { createdAt: "desc" } }); return NextResponse.json({ data: rows.map(map) }); } catch (e) { return apiErrorFromUnknown(e, "Không thể lấy danh sách gói tập."); } }
export async function POST(request: Request) { try { await requirePermission("member.create"); const b = await request.json(); const branchId = String(b.branchId ?? await defaultBranchId()).trim(); const duration = Number(b.duration); const price = Number(b.price); if (!branchId || !String(b.name ?? "").trim() || !duration || Number.isNaN(price)) return NextResponse.json({ message: "Thông tin gói tập không hợp lệ." }, { status: 400 }); const count = await prisma.gymPackage.count({ where: { branchId } }); const row = await prisma.gymPackage.create({ data: { branchId, code: `PKG-${String(count + 1).padStart(4, "0")}`, name: String(b.name).trim(), durationDays: duration * 30, price, status: b.status === "Tạm dừng" ? "INACTIVE" : "ACTIVE" } }); return NextResponse.json({ data: map(row) }, { status: 201 }); } catch (e) { return apiErrorFromUnknown(e, "Không thể tạo gói tập."); } }
export async function PATCH(request: Request) { try { await requirePermission("member.update"); const b = await request.json(); const ids = await getAccessibleBranchIds(); const existing = await prisma.gymPackage.findFirst({ where: { id: String(b.id), ...(ids === null ? {} : { branchId: { in: ids } }) } }); if (!existing) return NextResponse.json({ message: "Không tìm thấy gói tập." }, { status: 404 }); const row = await prisma.gymPackage.update({ where: { id: existing.id }, data: { name: String(b.name ?? existing.name).trim(), durationDays: Number(b.duration ?? existing.durationDays / 30) * 30, price: Number(b.price ?? existing.price), status: b.status === "Tạm dừng" ? "INACTIVE" : "ACTIVE" } }); return NextResponse.json({ data: map(row) }); } catch (e) { return apiErrorFromUnknown(e, "Không thể cập nhật gói tập."); } }
export async function DELETE(request: Request) { try { await requirePermission("member.update"); const b = await request.json(); const ids = await getAccessibleBranchIds(); const existing = await prisma.gymPackage.findFirst({ where: { id: String(b.id), ...(ids === null ? {} : { branchId: { in: ids } }) } }); if (!existing) return NextResponse.json({ message: "Không tìm thấy gói tập." }, { status: 404 }); await prisma.gymPackage.update({ where: { id: existing.id }, data: { status: "INACTIVE" } }); return NextResponse.json({ message: "Đã tạm dừng gói tập." }); } catch (e) { return apiErrorFromUnknown(e, "Không thể xóa gói tập."); } }
