import { NextResponse } from "next/server";
import { prisma } from "@/lib/db/prisma";
import { requirePermission, getAccessibleBranchIds } from "@/lib/auth/authorization";
import { defaultBranchId } from "@/lib/api/branches";
import { apiErrorFromUnknown } from "@/lib/api/response";
const typeMap: Record<string, "CALL" | "MESSAGE" | "CONSULTATION"> = { "Gọi điện": "CALL", "Nhắn tin": "MESSAGE", "Tư vấn": "CONSULTATION" }; const typeLabel = { CALL: "Gọi điện", MESSAGE: "Nhắn tin", CONSULTATION: "Tư vấn" }; const statusMap: Record<string, "PENDING" | "DONE"> = { "Chưa xử lý": "PENDING", "Đã xử lý": "DONE" }; const statusLabel = { PENDING: "Chưa xử lý", DONE: "Đã xử lý" };
const out = (x: any) => ({ id: x.id, member: x.member?.fullName ?? x.lead?.fullName ?? "", memberId: x.memberId ?? "", leadId: x.leadId ?? "", type: typeLabel[x.type as keyof typeof typeLabel], note: x.note ?? "", status: statusLabel[x.status as keyof typeof statusLabel], date: x.scheduledAt?.toISOString().slice(0, 10) ?? "" });
const include = { member: true, lead: true };
export async function GET() { try { await requirePermission("lead.read"); const ids = await getAccessibleBranchIds(); const rows = await prisma.crmActivity.findMany({ where: ids === null ? {} : { branchId: { in: ids } }, include, orderBy: { createdAt: "desc" } }); return NextResponse.json({ data: rows.map(out) }); } catch (e) { return apiErrorFromUnknown(e, "Không thể lấy lịch sử chăm sóc CRM."); } }
export async function POST(request: Request) { try { const user = await requirePermission("lead.create"); const b = await request.json(); const memberId = String(b.memberId ?? "").trim() || null; const leadId = String(b.leadId ?? "").trim() || null; const member = memberId ? await prisma.member.findUnique({ where: { id: memberId } }) : null; const lead = leadId ? await prisma.lead.findUnique({ where: { id: leadId } }) : null; const branchId = member?.branchId ?? lead?.branchId ?? await defaultBranchId(); if (!branchId || (!member && !lead)) return NextResponse.json({ message: "Phải chọn hội viên hoặc Lead hợp lệ." }, { status: 400 }); const row = await prisma.crmActivity.create({ data: { branchId, memberId: member?.id, leadId: lead?.id, createdById: user.id, type: typeMap[String(b.type)] ?? "CALL", note: String(b.note ?? "").trim() || null, status: statusMap[String(b.status)] ?? "PENDING", scheduledAt: b.date ? new Date(b.date) : null }, include }); return NextResponse.json({ data: out(row) }, { status: 201 }); } catch (e) { return apiErrorFromUnknown(e, "Không thể tạo hoạt động CRM."); } }
export async function PATCH(request: Request) { try { await requirePermission("lead.update"); const b = await request.json(); const row = await prisma.crmActivity.update({ where: { id: String(b.id) }, data: { type: typeMap[String(b.type)] ?? "CALL", note: String(b.note ?? "") || null, status: statusMap[String(b.status)] ?? "PENDING", scheduledAt: b.date ? new Date(b.date) : null }, include }); return NextResponse.json({ data: out(row) }); } catch (e) { return apiErrorFromUnknown(e, "Không thể cập nhật hoạt động CRM."); } }
export async function DELETE(request: Request) { try { await requirePermission("lead.delete"); const b = await request.json(); await prisma.crmActivity.delete({ where: { id: String(b.id) } }); return NextResponse.json({ message: "Đã xóa hoạt động CRM." }); } catch (e) { return apiErrorFromUnknown(e, "Không thể xóa hoạt động CRM."); } }