import { Router } from "express";
import { prisma } from "../db/prisma";
import { requirePermission,getAccessibleBranchIds } from "../auth/authorization";
import { hashPassword } from "../auth/password";
import { cacheDelete,cacheGet,cacheSet } from "../cache/valkey";
import { cacheKeys } from "../cache/keys";
import { defaultBranchId } from "../api/branches";
const out=(u:any)=>({id:u.id,name:u.fullName,email:u.email??"",phone:u.phone??"",specialty:u.trainerProfile?.specialty??"",status:u.isActive?"Đang hoạt động":"Tạm nghỉ"});
export const trainersRoutes=Router();
async function filter(req:any){const ids=await getAccessibleBranchIds(req);return ids===null?{}:{userBranches:{some:{branchId:{in:ids}}}};}
trainersRoutes.get("/",async(req,res)=>{try{await requirePermission(req,"trainer.read");const ids=await getAccessibleBranchIds(req);const rows=await prisma.user.findMany({where:{role:"TRAINER",userBranches:{some:{branchId:{in:ids}}}},orderBy:{createdAt:"desc"},include:{trainerProfile:true}});return res.json({data:rows.map(out),cached:false});}catch(error){const s=(error as any)?.status;if(s)return res.status(s).json({message:(error as any).message});return res.status(500).json({message:"Không thể lấy danh sách PT / Trainer."});}});
trainersRoutes.post("/",async(req,res)=>{try{await requirePermission(req,"trainer.create");const ids=await getAccessibleBranchIds(req),b=req.body??{},name=String(b.name??"").trim(),email=String(b.email??"").trim().toLowerCase(),phone=String(b.phone??"").trim(),password=String(b.password??"");if(!name||!phone||!email||password.length<8)return res.status(400).json({message:"Họ tên, email, số điện thoại và mật khẩu ít nhất 8 ký tự là bắt buộc."});if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({message:"Email Trainer không hợp lệ."});if(!/^\d{9,11}$/.test(phone.replace(/\s+/g,"")))return res.status(400).json({message:"Số điện thoại Trainer không hợp lệ."});const branchId=await defaultBranchId(req);if(!branchId)return res.status(400).json({message:"Chưa có chi nhánh để gán Trainer."});if(ids!==null&&!ids.includes(branchId))return res.status(403).json({message:"Bạn không có quyền tạo Trainer tại chi nhánh này."});const duplicate=await prisma.user.findFirst({where:{OR:[{email},{phone}]}});if(duplicate)return res.status(409).json({message:"Email hoặc số điện thoại đã tồn tại."});const u=await prisma.user.create({data:{fullName:name,email,phone,passwordHash:await hashPassword(password),role:"TRAINER",isActive:true,userBranches:{create:{branchId}},trainerProfile:{create:{specialty:String(b.specialty??"").trim()||null}}},include:{trainerProfile:true}});await cacheDelete(cacheKeys.trainers("all"));return res.status(201).json({data:out(u)});}catch(error){const s=(error as any)?.status;if(s)return res.status(s).json({message:(error as any).message});console.error("[trainers] create failed",error);return res.status(500).json({message:"Không thể tạo PT / Trainer."});}});
trainersRoutes.patch("/",async(req,res)=>{try{await requirePermission(req,"trainer.update");const ids=await getAccessibleBranchIds(req),b=req.body??{},id=String(b.id??"");const u=await prisma.user.findFirst({where:{id,role:"TRAINER",...(ids===null?{}:{userBranches:{some:{branchId:{in:ids}}}})},include:{trainerProfile:true}});if(!u)return res.status(404).json({message:"Không tìm thấy Trainer hoặc bạn không có quyền."});const email=String(b.email??u.email??"").trim().toLowerCase(),phone=String(b.phone??u.phone??"").trim();if(!email||!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({message:"Email Trainer không hợp lệ."});if(!phone||!/^\d{9,11}$/.test(phone.replace(/\s+/g,"")))return res.status(400).json({message:"Số điện thoại Trainer không hợp lệ."});const dup=await prisma.user.findFirst({where:{id:{not:id},OR:[{email},{phone}]}});if(dup)return res.status(409).json({message:"Email hoặc số điện thoại đã được sử dụng."});const updated=await prisma.user.update({where:{id},data:{fullName:String(b.name??u.fullName).trim(),email,phone,isActive:b.status===undefined?u.isActive:b.status==="Đang hoạt động",trainerProfile:{upsert:{create:{specialty:String(b.specialty??"").trim()||null},update:{specialty:String(b.specialty??u.trainerProfile?.specialty??"").trim()||null}}}},include:{trainerProfile:true}});await cacheDelete(cacheKeys.trainers("all"));return res.json({data:out(updated)});}catch(error){const s=(error as any)?.status;if(s)return res.status(s).json({message:(error as any).message});console.error("[trainers] update failed",error);return res.status(500).json({message:"Không thể cập nhật PT / Trainer."});}});
trainersRoutes.delete("/",async(req,res)=>{try{await requirePermission(req,"trainer.delete");const ids=await getAccessibleBranchIds(req),id=String(req.body?.id??""),u=await prisma.user.findFirst({where:{id,role:"TRAINER",...(ids===null?{}:{userBranches:{some:{branchId:{in:ids}}}})},select:{id:true}});if(!u)return res.status(404).json({message:"Không tìm thấy Trainer hoặc bạn không có quyền."});await prisma.user.update({where:{id},data:{isActive:false}});await cacheDelete(cacheKeys.trainers("all"));return res.json({message:"Đã ngừng hoạt động Trainer."});}catch(error){const s=(error as any)?.status;if(s)return res.status(s).json({message:(error as any).message});console.error("[trainers] delete failed",error);return res.status(500).json({message:"Không thể xóa Trainer."});}});
